spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password:
  kafka:
    consumer:
        properties:
          spring:
            json:
              trusted:
                packages: 
                - br.com.sanfelice.microservices 
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false
    bootstrap-servers: localhost:9092
    topic:
      userCreated: USER_CREATED_TOPIC
security:
  basic:
    enabled: false