spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      userCreated: USER_CREATED_TOPIC
    consumer:
      group-id: mail_consumer
      properties:
        spring:
          json:
            trusted:
              packages: 
              - br.com.sanfelice.microservices 
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_GMAIL_USERNAME
    password: YOUR_GMAIL_PASSWORD
    properties.mail.smtp:
      auth: true
      starttls.enable: true
security:
  basic:
    enabled: false

    